package shortener

import (
	"context"
	"errors"
	"testing"

	"urlshortener/internal/auth"
)

// --- Mocks ---

type mockURLRepo struct {
	existsFunc      func(code string) (bool, error)
	createFunc      func(url *ShortURL) error
	findByID        func(id string) (*ShortURL, error)
	updateFunc      func(url *ShortURL) error
	deleteFunc      func(id, ownerID string) error
	countActiveFunc func(ownerID string) (int64, error)
	createdURLs     []*ShortURL
	createCalls     int
	existsCalls     int
	deletedIDs      []string
	updatedURLs     []*ShortURL
}

func (m *mockURLRepo) CountActiveByOwner(_ context.Context, ownerID string) (int64, error) {
	if m.countActiveFunc != nil {
		return m.countActiveFunc(ownerID)
	}
	return 0, nil
}

// mockUserRepo implementa auth.UserRepository; solo FindByID importa para el plan.
type mockUserRepo struct {
	plan auth.Plan
}

func (m *mockUserRepo) Create(context.Context, *auth.User) error { return nil }
func (m *mockUserRepo) FindByEmail(context.Context, string) (*auth.User, error) {
	return nil, auth.ErrUserNotFound
}
func (m *mockUserRepo) FindByID(_ context.Context, id string) (*auth.User, error) {
	return &auth.User{ID: id, Plan: m.plan}, nil
}
func (m *mockUserRepo) UpdatePlan(context.Context, string, auth.Plan) error  { return nil }
func (m *mockUserRepo) UpdatePassword(context.Context, string, string) error { return nil }
func (m *mockUserRepo) Delete(context.Context, string) error                 { return nil }

// testBaseURL es el dominio propio usado en los tests del validador de URL.
const testBaseURL = "http://localhost:8080"

// newSvc construye el service con un usuario Pro (sin límite de plan): así los
// tests existentes de creación/colisión no se ven afectados por el cupo. Los tests
// de plan usan newPlanSvc con el plan y el límite explícitos.
func newSvc(repo URLRepository, cache CacheRepository) ShortenerService {
	return NewShortenerService(repo, cache, &mockUserRepo{plan: auth.PlanPro}, 5, testBaseURL)
}

func newPlanSvc(repo URLRepository, cache CacheRepository, plan auth.Plan, max int) ShortenerService {
	return NewShortenerService(repo, cache, &mockUserRepo{plan: plan}, max, testBaseURL)
}

func (m *mockURLRepo) Create(_ context.Context, url *ShortURL) error {
	m.createCalls++
	m.createdURLs = append(m.createdURLs, url)
	if m.createFunc != nil {
		return m.createFunc(url)
	}
	return nil
}
func (m *mockURLRepo) FindByCode(_ context.Context, _ string) (*ShortURL, error) {
	return nil, ErrURLNotFound
}
func (m *mockURLRepo) FindByID(_ context.Context, id string) (*ShortURL, error) {
	if m.findByID != nil {
		return m.findByID(id)
	}
	return nil, ErrURLNotFound
}
func (m *mockURLRepo) FindByOwner(_ context.Context, _ string, _ ListFilter, _, _ int) ([]*ShortURL, int64, error) {
	return nil, 0, nil
}
func (m *mockURLRepo) ExistsByCode(_ context.Context, code string) (bool, error) {
	m.existsCalls++
	if m.existsFunc != nil {
		return m.existsFunc(code)
	}
	return false, nil
}
func (m *mockURLRepo) Update(_ context.Context, url *ShortURL) error {
	m.updatedURLs = append(m.updatedURLs, url)
	if m.updateFunc != nil {
		return m.updateFunc(url)
	}
	return nil
}
func (m *mockURLRepo) Delete(_ context.Context, id, ownerID string) error {
	m.deletedIDs = append(m.deletedIDs, id)
	if m.deleteFunc != nil {
		return m.deleteFunc(id, ownerID)
	}
	return nil
}
func (m *mockURLRepo) IncrementClicks(context.Context, string) error           { return nil }
func (m *mockURLRepo) SumClicksByOwner(context.Context, string) (int64, error) { return 0, nil }
func (m *mockURLRepo) FindShortCodesByOwner(context.Context, string) ([]string, error) {
	return nil, nil
}
func (m *mockURLRepo) DeleteAllByOwner(context.Context, string) error { return nil }

type mockCache struct {
	store   map[string]string
	setKeys []string
	delKeys []string
}

func newMockCache() *mockCache {
	return &mockCache{store: map[string]string{}}
}
func (m *mockCache) Set(_ context.Context, code, originalURL string) error {
	m.store[code] = originalURL
	m.setKeys = append(m.setKeys, code)
	return nil
}
func (m *mockCache) Get(_ context.Context, code string) (string, error) {
	v, ok := m.store[code]
	if !ok {
		return "", ErrCacheMiss
	}
	return v, nil
}
func (m *mockCache) Delete(_ context.Context, code string) error {
	delete(m.store, code)
	m.delKeys = append(m.delKeys, code)
	return nil
}

// --- Tests de CreateShortURL ---

func TestCreate_Autogenerated_Success(t *testing.T) {
	repo := &mockURLRepo{existsFunc: func(string) (bool, error) { return false, nil }}
	cache := newMockCache()
	svc := newSvc(repo, cache)

	url, err := svc.CreateShortURL(context.Background(), "owner1", "https://go.dev", nil)
	if err != nil {
		t.Fatalf("esperaba éxito, obtuvo %v", err)
	}
	if url.ShortCode == "" || url.IsCustomAlias {
		t.Fatalf("código autogenerado inesperado: %+v", url)
	}
	if repo.createCalls != 1 {
		t.Fatalf("esperaba 1 Create, hubo %d", repo.createCalls)
	}
	if cache.store[url.ShortCode] != "https://go.dev" {
		t.Fatal("el cache no se pobló tras crear")
	}
}

func TestCreate_CustomAlias_Success(t *testing.T) {
	repo := &mockURLRepo{existsFunc: func(string) (bool, error) { return false, nil }}
	cache := newMockCache()
	svc := newSvc(repo, cache)

	alias := "mi-promo"
	url, err := svc.CreateShortURL(context.Background(), "owner1", "https://go.dev", &alias)
	if err != nil {
		t.Fatalf("esperaba éxito, obtuvo %v", err)
	}
	if url.ShortCode != alias || !url.IsCustomAlias {
		t.Fatalf("alias no aplicado: %+v", url)
	}
}

func TestCreate_AliasTaken_NoRetry(t *testing.T) {
	repo := &mockURLRepo{existsFunc: func(string) (bool, error) { return true, nil }}
	svc := newSvc(repo, newMockCache())

	alias := "tomado"
	_, err := svc.CreateShortURL(context.Background(), "owner1", "https://go.dev", &alias)
	if !errors.Is(err, ErrAliasTaken) {
		t.Fatalf("esperaba ErrAliasTaken, obtuvo %v", err)
	}
	if repo.createCalls != 0 {
		t.Fatalf("no debía intentar crear con alias tomado, hubo %d Create", repo.createCalls)
	}
	if repo.existsCalls != 1 {
		t.Fatalf("alias tomado no debe reintentar: esperaba 1 ExistsByCode, hubo %d", repo.existsCalls)
	}
}

func TestCreate_RetryExhaustion(t *testing.T) {
	// ExistsByCode siempre true => toda generación colisiona => ErrCodeGenFailed.
	repo := &mockURLRepo{existsFunc: func(string) (bool, error) { return true, nil }}
	svc := newSvc(repo, newMockCache())

	_, err := svc.CreateShortURL(context.Background(), "owner1", "https://go.dev", nil)
	if !errors.Is(err, ErrCodeGenFailed) {
		t.Fatalf("esperaba ErrCodeGenFailed, obtuvo %v", err)
	}
	if repo.createCalls != 0 {
		t.Fatalf("no debía crear si todas colisionan, hubo %d Create", repo.createCalls)
	}
	if repo.existsCalls != maxRetries {
		t.Fatalf("esperaba %d intentos, hubo %d", maxRetries, repo.existsCalls)
	}
}

func TestCreate_RetryRecoversFromCollision(t *testing.T) {
	// Primera colisión, segunda libre.
	calls := 0
	repo := &mockURLRepo{existsFunc: func(string) (bool, error) {
		calls++
		return calls == 1, nil // colisiona solo la primera vez
	}}
	svc := newSvc(repo, newMockCache())

	url, err := svc.CreateShortURL(context.Background(), "owner1", "https://go.dev", nil)
	if err != nil {
		t.Fatalf("esperaba éxito tras reintento, obtuvo %v", err)
	}
	if url.ShortCode == "" {
		t.Fatal("código vacío")
	}
	if repo.createCalls != 1 {
		t.Fatalf("esperaba 1 Create exitoso, hubo %d", repo.createCalls)
	}
}

func TestCheckAlias(t *testing.T) {
	repo := &mockURLRepo{}
	svc := newSvc(repo, newMockCache())

	repo.existsFunc = func(string) (bool, error) { return true, nil }
	if avail, _ := svc.CheckAliasAvailability(context.Background(), "tomado"); avail {
		t.Fatal("alias existente debería ser no disponible")
	}
	repo.existsFunc = func(string) (bool, error) { return false, nil }
	if avail, _ := svc.CheckAliasAvailability(context.Background(), "libre"); !avail {
		t.Fatal("alias inexistente debería estar disponible")
	}
	// Formato inválido: no disponible y sin tocar el repo.
	if avail, _ := svc.CheckAliasAvailability(context.Background(), "x"); avail {
		t.Fatal("alias con formato inválido no debe estar disponible")
	}
}

func TestToggleActive_DeactivateRemovesFromCache(t *testing.T) {
	owned := &ShortURL{ID: "id1", ShortCode: "abc123", OriginalURL: "https://go.dev", OwnerID: "owner1", IsActive: true}
	repo := &mockURLRepo{findByID: func(string) (*ShortURL, error) { return owned, nil }}
	cache := newMockCache()
	cache.store["abc123"] = "https://go.dev"
	svc := newSvc(repo, cache)

	if err := svc.ToggleActive(context.Background(), "owner1", "id1", false); err != nil {
		t.Fatalf("toggle falló: %v", err)
	}
	if _, ok := cache.store["abc123"]; ok {
		t.Fatal("al desactivar, la entrada debe desaparecer de Redis")
	}
	if len(cache.delKeys) != 1 || cache.delKeys[0] != "abc123" {
		t.Fatalf("esperaba Delete del código en cache, hubo %v", cache.delKeys)
	}
}

func TestToggleActive_ActivateRepopulatesCache(t *testing.T) {
	owned := &ShortURL{ID: "id1", ShortCode: "abc123", OriginalURL: "https://go.dev", OwnerID: "owner1", IsActive: false}
	repo := &mockURLRepo{findByID: func(string) (*ShortURL, error) { return owned, nil }}
	cache := newMockCache()
	svc := newSvc(repo, cache)

	if err := svc.ToggleActive(context.Background(), "owner1", "id1", true); err != nil {
		t.Fatalf("toggle falló: %v", err)
	}
	if cache.store["abc123"] != "https://go.dev" {
		t.Fatal("al activar, la entrada debe repoblarse en Redis")
	}
}

// --- Ownership: no-owner => ErrNotOwner, no leak de existencia ---

func TestToggleAndDelete_NotOwner(t *testing.T) {
	other := &ShortURL{ID: "id1", ShortCode: "abc123", OwnerID: "someoneElse", IsActive: true}
	repo := &mockURLRepo{findByID: func(string) (*ShortURL, error) { return other, nil }}
	svc := newSvc(repo, newMockCache())

	if err := svc.ToggleActive(context.Background(), "intruder", "id1", false); !errors.Is(err, ErrNotOwner) {
		t.Fatalf("toggle ajeno: esperaba ErrNotOwner, obtuvo %v", err)
	}
	if err := svc.DeleteURL(context.Background(), "intruder", "id1"); !errors.Is(err, ErrNotOwner) {
		t.Fatalf("delete ajeno: esperaba ErrNotOwner, obtuvo %v", err)
	}
}

func TestDelete_NonexistentIsNotOwner(t *testing.T) {
	// Un id inexistente devuelve ErrNotOwner (403), no ErrURLNotFound (404),
	// para no filtrar si el id existe.
	repo := &mockURLRepo{findByID: func(string) (*ShortURL, error) { return nil, ErrURLNotFound }}
	svc := newSvc(repo, newMockCache())

	if err := svc.DeleteURL(context.Background(), "owner1", "missing"); !errors.Is(err, ErrNotOwner) {
		t.Fatalf("esperaba ErrNotOwner para id inexistente, obtuvo %v", err)
	}
}

func TestDelete_OwnerSuccess(t *testing.T) {
	owned := &ShortURL{ID: "id1", ShortCode: "abc123", OwnerID: "owner1"}
	repo := &mockURLRepo{findByID: func(string) (*ShortURL, error) { return owned, nil }}
	cache := newMockCache()
	cache.store["abc123"] = "https://go.dev"
	svc := newSvc(repo, cache)

	if err := svc.DeleteURL(context.Background(), "owner1", "id1"); err != nil {
		t.Fatalf("delete propio falló: %v", err)
	}
	if len(repo.deletedIDs) != 1 {
		t.Fatalf("esperaba 1 Delete en Mongo, hubo %d", len(repo.deletedIDs))
	}
	if _, ok := cache.store["abc123"]; ok {
		t.Fatal("la entrada debe eliminarse de Redis al borrar")
	}
}

func TestCreate_FreePlanAtLimit_Rejected(t *testing.T) {
	repo := &mockURLRepo{
		existsFunc:      func(string) (bool, error) { return false, nil },
		countActiveFunc: func(string) (int64, error) { return 5, nil },
	}
	cache := newMockCache()
	svc := newPlanSvc(repo, cache, auth.PlanFree, 5)

	_, err := svc.CreateShortURL(context.Background(), "owner1", "https://go.dev", nil)
	if !errors.Is(err, auth.ErrPlanLimitExceeded) {
		t.Fatalf("esperaba ErrPlanLimitExceeded, obtuvo %v", err)
	}
	if repo.createCalls != 0 {
		t.Fatalf("no debe crearse nada en Mongo, hubo %d Create", repo.createCalls)
	}
	if repo.existsCalls != 0 {
		t.Fatalf("no debe generarse ningún código (ExistsByCode), hubo %d", repo.existsCalls)
	}
	if len(cache.setKeys) != 0 {
		t.Fatalf("no debe tocarse Redis, hubo %v", cache.setKeys)
	}
}

func TestCreate_FreePlanUnderLimit_Allowed(t *testing.T) {
	repo := &mockURLRepo{
		existsFunc:      func(string) (bool, error) { return false, nil },
		countActiveFunc: func(string) (int64, error) { return 4, nil },
	}
	svc := newPlanSvc(repo, newMockCache(), auth.PlanFree, 5)

	if _, err := svc.CreateShortURL(context.Background(), "owner1", "https://go.dev", nil); err != nil {
		t.Fatalf("4 activas con límite 5 debe permitir crear, obtuvo %v", err)
	}
	if repo.createCalls != 1 {
		t.Fatalf("esperaba 1 Create, hubo %d", repo.createCalls)
	}
}

// Pro nunca se limita aunque tenga muchas URLs activas.
func TestCreate_ProPlan_NoLimit(t *testing.T) {
	repo := &mockURLRepo{
		existsFunc:      func(string) (bool, error) { return false, nil },
		countActiveFunc: func(string) (int64, error) { return 999, nil },
	}
	svc := newPlanSvc(repo, newMockCache(), auth.PlanPro, 5)

	if _, err := svc.CreateShortURL(context.Background(), "owner1", "https://go.dev", nil); err != nil {
		t.Fatalf("Pro no debe tener límite, obtuvo %v", err)
	}
	if repo.createCalls != 1 {
		t.Fatalf("esperaba 1 Create, hubo %d", repo.createCalls)
	}
}

// Reactivar con 5 activas (max 5): pasaría a 6, se rechaza y NO se actualiza.
func TestToggleActive_FreeReactivateAtLimit_Rejected(t *testing.T) {
	inactive := &ShortURL{ID: "id1", ShortCode: "abc123", OriginalURL: "https://go.dev", OwnerID: "owner1", IsActive: false}
	repo := &mockURLRepo{
		findByID:        func(string) (*ShortURL, error) { return inactive, nil },
		countActiveFunc: func(string) (int64, error) { return 5, nil },
	}
	svc := newPlanSvc(repo, newMockCache(), auth.PlanFree, 5)

	err := svc.ToggleActive(context.Background(), "owner1", "id1", true)
	if !errors.Is(err, auth.ErrPlanLimitExceeded) {
		t.Fatalf("esperaba ErrPlanLimitExceeded al reactivar en el límite, obtuvo %v", err)
	}
	if len(repo.updatedURLs) != 0 {
		t.Fatalf("no debe actualizarse la URL si excede el cupo, hubo %d Update", len(repo.updatedURLs))
	}
}

// Reactivar con 4 activas (max 5): llega justo a 5, se permite.
func TestToggleActive_FreeReactivateJustUnderLimit_Allowed(t *testing.T) {
	inactive := &ShortURL{ID: "id1", ShortCode: "abc123", OriginalURL: "https://go.dev", OwnerID: "owner1", IsActive: false}
	repo := &mockURLRepo{
		findByID:        func(string) (*ShortURL, error) { return inactive, nil },
		countActiveFunc: func(string) (int64, error) { return 4, nil },
	}
	svc := newPlanSvc(repo, newMockCache(), auth.PlanFree, 5)

	if err := svc.ToggleActive(context.Background(), "owner1", "id1", true); err != nil {
		t.Fatalf("4 activas con límite 5 debe permitir reactivar, obtuvo %v", err)
	}
	if len(repo.updatedURLs) != 1 {
		t.Fatalf("esperaba 1 Update, hubo %d", len(repo.updatedURLs))
	}
}

// Desactivar nunca consume cupo: aún en el límite, desactivar funciona.
func TestToggleActive_FreeDeactivate_NotQuotaChecked(t *testing.T) {
	active := &ShortURL{ID: "id1", ShortCode: "abc123", OriginalURL: "https://go.dev", OwnerID: "owner1", IsActive: true}
	repo := &mockURLRepo{
		findByID: func(string) (*ShortURL, error) { return active, nil },
		countActiveFunc: func(string) (int64, error) {
			t.Fatal("desactivar no debe consultar el cupo")
			return 0, nil
		},
	}
	svc := newPlanSvc(repo, newMockCache(), auth.PlanFree, 5)

	if err := svc.ToggleActive(context.Background(), "owner1", "id1", false); err != nil {
		t.Fatalf("desactivar no debe estar limitado, obtuvo %v", err)
	}
}

// Caso límite: activar una URL YA activa (no-op) estando en el límite no debe
// rechazarse, porque el conteo de activas no cambia.
func TestToggleActive_FreeAlreadyActiveAtLimit_NotRejected(t *testing.T) {
	active := &ShortURL{ID: "id1", ShortCode: "abc123", OriginalURL: "https://go.dev", OwnerID: "owner1", IsActive: true}
	repo := &mockURLRepo{
		findByID: func(string) (*ShortURL, error) { return active, nil },
		countActiveFunc: func(string) (int64, error) {
			t.Fatal("un no-op (ya activa) no debe consultar el cupo")
			return 5, nil
		},
	}
	svc := newPlanSvc(repo, newMockCache(), auth.PlanFree, 5)

	if err := svc.ToggleActive(context.Background(), "owner1", "id1", true); err != nil {
		t.Fatalf("activar una URL ya activa no debe rechazarse, obtuvo %v", err)
	}
}
