/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Registrar un usuario nuevo
         * @description Crea el usuario (plan Free por defecto) e inmediatamente emite un par de tokens.
         *     Rate limit por IP (`AUTH_RATE_LIMIT_PER_MIN`).
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["RegisterRequest"];
                };
            };
            responses: {
                /** @description Usuario creado y autenticado */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Envelope"] & {
                            data?: components["schemas"]["AuthResponse"];
                        };
                    };
                };
                400: components["responses"]["ValidationError"];
                /** @description Email ya registrado (`AUTH_EMAIL_TAKEN`) */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorEnvelope"];
                    };
                };
                429: components["responses"]["RateLimited"];
                500: components["responses"]["InternalError"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Iniciar sesión
         * @description Devuelve el mismo error (`AUTH_INVALID_CREDENTIALS`) tanto si el email no existe
         *     como si la contraseña es incorrecta (no filtra existencia). Rate limit por IP.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["LoginRequest"];
                };
            };
            responses: {
                /** @description Autenticado */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Envelope"] & {
                            data?: components["schemas"]["AuthResponse"];
                        };
                    };
                };
                400: components["responses"]["ValidationError"];
                /** @description Credenciales inválidas (`AUTH_INVALID_CREDENTIALS`) */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorEnvelope"];
                    };
                };
                429: components["responses"]["RateLimited"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Renovar el access token
         * @description Recibe un refresh token válido y emite un nuevo access token.
         *     La respuesta solo trae `accessToken` (sin `refreshToken` ni `user`).
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["RefreshRequest"];
                };
            };
            responses: {
                /** @description Nuevo access token emitido */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Envelope"] & {
                            data?: components["schemas"]["AuthResponse"];
                        };
                    };
                };
                400: components["responses"]["ValidationError"];
                /** @description Refresh token expirado (`AUTH_TOKEN_EXPIRED`) o inválido (`AUTH_TOKEN_INVALID`) */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorEnvelope"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Datos del usuario autenticado */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Usuario actual */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Envelope"] & {
                            data?: components["schemas"]["UserDTO"];
                        };
                    };
                };
                401: components["responses"]["Unauthorized"];
            };
        };
        put?: never;
        post?: never;
        /**
         * Eliminar la propia cuenta
         * @description Exige la contraseña actual. Orquesta el borrado en cascada: purga el cache de
         *     redirección de cada URL, elimina todas las URLs del usuario en Mongo y luego el
         *     usuario. Los clics históricos en InfluxDB **no** se eliminan (fuera de alcance).
         */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["DeleteAccountRequest"];
                };
            };
            responses: {
                200: components["responses"]["EmptySuccess"];
                400: components["responses"]["ValidationError"];
                /** @description Contraseña incorrecta (`AUTH_INVALID_CREDENTIALS`) o token inválido (`AUTH_TOKEN_INVALID`) */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorEnvelope"];
                    };
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/me/plan": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Cambiar el plan del propio usuario
         * @description Herramienta de prueba mientras no hay pasarela de pago: cualquier usuario
         *     autenticado puede cambiar su propio plan. Devuelve el usuario actualizado.
         */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["UpdatePlanRequest"];
                };
            };
            responses: {
                /** @description Plan actualizado */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Envelope"] & {
                            data?: components["schemas"]["UserDTO"];
                        };
                    };
                };
                400: components["responses"]["ValidationError"];
                401: components["responses"]["Unauthorized"];
            };
        };
        trace?: never;
    };
    "/api/v1/auth/me/password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Cambiar la contraseña
         * @description Verifica la contraseña actual antes de reemplazarla.
         */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["ChangePasswordRequest"];
                };
            };
            responses: {
                200: components["responses"]["EmptySuccess"];
                400: components["responses"]["ValidationError"];
                /** @description Contraseña actual incorrecta (`AUTH_INVALID_CREDENTIALS`) o token inválido (`AUTH_TOKEN_INVALID`) */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorEnvelope"];
                    };
                };
            };
        };
        trace?: never;
    };
    "/api/v1/auth/me/summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Resumen de cuenta
         * @description Plan, límite de URLs activas (null si Pro), conteo de activas y total de clics.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Resumen de cuenta */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Envelope"] & {
                            data?: components["schemas"]["AccountSummaryResponse"];
                        };
                    };
                };
                401: components["responses"]["Unauthorized"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/urls": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Listar las URLs del usuario (paginado) */
        get: {
            parameters: {
                query?: {
                    /** @description Página (default 1) */
                    page?: components["parameters"]["Page"];
                    /** @description Tamaño de página (default 20, máximo 100, se clampea) */
                    limit?: components["parameters"]["Limit"];
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Página de URLs del usuario */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Envelope"] & {
                            data?: components["schemas"]["URLResponse"][];
                            meta?: components["schemas"]["Meta"];
                        };
                    };
                };
                401: components["responses"]["Unauthorized"];
            };
        };
        put?: never;
        /**
         * Crear una URL corta
         * @description Crea una URL con código autogenerado o con alias propio (`customAlias`).
         *     Valida la URL original (esquema http/https, no hosts locales/privados, no el
         *     propio dominio del servicio) antes de tocar la base de datos. El plan Free está
         *     limitado en número de URLs activas (`PLAN_LIMIT_EXCEEDED`). Rate limit por usuario.
         *     La respuesta incluye el `qrCodeBase64` (QR generado on-demand, no persistido).
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["CreateURLRequest"];
                };
            };
            responses: {
                /** @description URL creada */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Envelope"] & {
                            data?: components["schemas"]["URLResponse"];
                        };
                    };
                };
                /** @description Body inválido (`VALIDATION_ERROR`) o URL no permitida (`INVALID_URL`) */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorEnvelope"];
                    };
                };
                401: components["responses"]["Unauthorized"];
                /** @description Cupo del plan Free alcanzado (`PLAN_LIMIT_EXCEEDED`) */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorEnvelope"];
                    };
                };
                /** @description El alias ya está en uso (`ALIAS_TAKEN`) */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorEnvelope"];
                    };
                };
                429: components["responses"]["RateLimited"];
                500: components["responses"]["InternalError"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/urls/check-alias": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Comprobar disponibilidad de un alias */
        get: {
            parameters: {
                query: {
                    alias: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Disponibilidad del alias */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Envelope"] & {
                            data?: components["schemas"]["CheckAliasResponse"];
                        };
                    };
                };
                400: components["responses"]["ValidationError"];
                401: components["responses"]["Unauthorized"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/urls/code/{shortCode}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Detalle de una URL por shortCode
         * @description Devuelve los metadatos + QR de una sola URL del usuario. Alimenta la pantalla
         *     de detalle del frontend. Una URL ajena o inexistente devuelve `FORBIDDEN`
         *     (mismo error, no filtra existencia).
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    shortCode: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Datos de la URL */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Envelope"] & {
                            data?: components["schemas"]["URLResponse"];
                        };
                    };
                };
                401: components["responses"]["Unauthorized"];
                /** @description No es tu URL o no existe (`FORBIDDEN`) */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorEnvelope"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/urls/{id}/active": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Activar/desactivar una URL
         * @description Sincroniza el cache de redirección. Reactivar consume cupo del plan (puede
         *     devolver `PLAN_LIMIT_EXCEEDED`). Una URL ajena o inexistente devuelve `FORBIDDEN`
         *     (mismo error, no filtra existencia).
         */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description ID hex de la URL (ObjectID de Mongo) */
                    id: components["parameters"]["UrlId"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["ToggleActiveRequest"];
                };
            };
            responses: {
                200: components["responses"]["EmptySuccess"];
                400: components["responses"]["ValidationError"];
                401: components["responses"]["Unauthorized"];
                /** @description No es tu URL o no existe (`FORBIDDEN`); o cupo alcanzado al reactivar (`PLAN_LIMIT_EXCEEDED`) */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorEnvelope"];
                    };
                };
            };
        };
        trace?: never;
    };
    "/api/v1/urls/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Eliminar una URL
         * @description Una URL ajena o inexistente devuelve `FORBIDDEN` (no filtra existencia).
         */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description ID hex de la URL (ObjectID de Mongo) */
                    id: components["parameters"]["UrlId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: components["responses"]["EmptySuccess"];
                401: components["responses"]["Unauthorized"];
                /** @description No es tu URL o no existe (`FORBIDDEN`) */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorEnvelope"];
                    };
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/analytics/stats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Métricas agregadas
         * @description Con `shortCode` devuelve las métricas de esa URL (`FORBIDDEN` si no es tuya);
         *     sin él, el overview de todas tus URLs. El plan Free está limitado al rango `24h`
         *     (`PLAN_RANGE_NOT_ALLOWED` si pide 7d/30d).
         */
        get: {
            parameters: {
                query?: {
                    /** @description Código de la URL; si se omite, vista overview de todas las del usuario */
                    shortCode?: components["parameters"]["ShortCodeQuery"];
                    /** @description Rango temporal (default 24h) */
                    range?: components["parameters"]["RangeQuery"];
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Métricas */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Envelope"] & {
                            data?: components["schemas"]["StatsResponse"];
                        };
                    };
                };
                /** @description Rango inválido o params mal formados (`VALIDATION_ERROR`) */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorEnvelope"];
                    };
                };
                401: components["responses"]["Unauthorized"];
                /** @description URL ajena (`FORBIDDEN`) o rango no permitido para el plan (`PLAN_RANGE_NOT_ALLOWED`) */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorEnvelope"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/analytics/stats/export": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Exportar métricas a CSV
         * @description Mismas métricas y validaciones que `/analytics/stats`, pero el camino feliz
         *     responde un archivo CSV crudo (BOM UTF-8 + CRLF para Excel), **no** el envelope
         *     JSON. Los errores sí usan el envelope JSON estándar.
         */
        get: {
            parameters: {
                query?: {
                    /** @description Código de la URL; si se omite, vista overview de todas las del usuario */
                    shortCode?: components["parameters"]["ShortCodeQuery"];
                    /** @description Rango temporal (default 24h) */
                    range?: components["parameters"]["RangeQuery"];
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Archivo CSV (Content-Disposition de descarga) */
                200: {
                    headers: {
                        /** @description attachment; filename="stats-<label>-<range>.csv" */
                        "Content-Disposition"?: string;
                        [name: string]: unknown;
                    };
                    content: {
                        "text/csv": string;
                    };
                };
                /** @description Params inválidos (`VALIDATION_ERROR`) */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorEnvelope"];
                    };
                };
                401: components["responses"]["Unauthorized"];
                /** @description URL ajena (`FORBIDDEN`) o rango no permitido para el plan (`PLAN_RANGE_NOT_ALLOWED`) */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorEnvelope"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/{code}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Redirigir una URL corta
         * @description Endpoint público en la raíz. Resuelve el código (Redis primero, fallback a
         *     Mongo) y responde `302` con `Location`. El registro del clic y el incremento del
         *     contador son asíncronos y no afectan la respuesta. Rate limit por IP.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    code: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Redirección a la URL original */
                302: {
                    headers: {
                        /** @description URL original de destino */
                        Location?: string;
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Código inexistente (`URL_NOT_FOUND`) */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorEnvelope"];
                    };
                };
                /** @description URL desactivada (`URL_INACTIVE`) */
                410: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorEnvelope"];
                    };
                };
                429: components["responses"]["RateLimited"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Healthcheck
         * @description Readiness probe. **No** usa el envelope estándar: responde un JSON plano
         *     `{ "status": "ok" }`.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Servicio operativo */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @example ok */
                            status?: string;
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @description Sobre común de toda respuesta JSON de la API. */
        Envelope: {
            success: boolean;
            /**
             * @description Payload del endpoint (su forma se especializa por respuesta vía allOf).
             *     Es `null` cuando `success` es false.
             */
            data: unknown;
            /** @description Poblado solo cuando `success` es false; `null` en caso de éxito. */
            error: components["schemas"]["ApiError"];
            /** @description Presente solo en respuestas paginadas. */
            meta?: components["schemas"]["Meta"];
        };
        /** @description Envelope de error (success: false, data: null, error poblado). */
        ErrorEnvelope: {
            /** @example false */
            success: boolean;
            /**
             * @description Siempre null en una respuesta de error.
             * @example null
             */
            data: unknown;
            error: components["schemas"]["ApiError"];
        };
        ApiError: {
            /**
             * @description Código de error estable
             * @example VALIDATION_ERROR
             */
            code: string;
            /** @example Cuerpo de la solicitud inválido. */
            message: string;
        };
        /** @description Bloque de paginación (solo en listados). */
        Meta: {
            /** @example 1 */
            page: number;
            /** @example 20 */
            limit: number;
            /**
             * Format: int64
             * @example 134
             */
            total: number;
            /** @example 7 */
            totalPages: number;
        };
        RegisterRequest: {
            /** Format: email */
            email: string;
            /** @example superSecret1 */
            password: string;
        };
        LoginRequest: {
            /** Format: email */
            email: string;
            password: string;
        };
        RefreshRequest: {
            refreshToken: string;
        };
        UpdatePlanRequest: {
            /** @enum {string} */
            plan: "free" | "pro";
        };
        ChangePasswordRequest: {
            currentPassword: string;
            newPassword: string;
        };
        DeleteAccountRequest: {
            password: string;
        };
        /**
         * @description En register/login trae accessToken + refreshToken + user. En refresh solo
         *     trae accessToken (refreshToken y user se omiten).
         */
        AuthResponse: {
            accessToken: string;
            refreshToken?: string;
            user?: components["schemas"]["UserDTO"];
        };
        UserDTO: {
            id: string;
            /** Format: email */
            email: string;
            /** @enum {string} */
            plan: "free" | "pro";
        };
        AccountSummaryResponse: {
            /** Format: email */
            email: string;
            /** @enum {string} */
            plan: "free" | "pro";
            /** Format: date-time */
            createdAt: string;
            /** Format: int64 */
            activeUrlsCount: number;
            /** @description Límite de URLs activas del plan Free; null si Pro (ilimitado). */
            activeUrlsLimit?: number | null;
            /** Format: int64 */
            totalClicks: number;
        };
        CreateURLRequest: {
            /**
             * Format: uri
             * @example https://google.com
             */
            originalUrl: string;
            /**
             * @description Alias alfanumérico opcional; si se omite, se autogenera un código.
             * @example mi-promo
             */
            customAlias?: string | null;
        };
        URLResponse: {
            id: string;
            /** @example xYz12A */
            shortCode: string;
            /**
             * Format: uri
             * @example http://localhost:8080/xYz12A
             */
            shortUrl: string;
            /** Format: uri */
            originalUrl: string;
            isCustomAlias: boolean;
            isActive: boolean;
            /** Format: date-time */
            createdAt: string;
            /**
             * Format: int64
             * @description Contador aproximado de clics de la URL (fire-and-forget; la verdad fina está en InfluxDB).
             */
            totalClicks: number;
            /** @description QR del shortUrl como data URI (data:image/png;base64,...). Vacío si falló su generación. */
            qrCodeBase64: string;
        };
        CheckAliasResponse: {
            alias: string;
            available: boolean;
        };
        ToggleActiveRequest: {
            isActive: boolean;
        };
        StatsResponse: {
            /** @enum {string} */
            range: "24h" | "7d" | "30d";
            stats: components["schemas"]["ClickStats"];
        };
        ClickStats: {
            /** Format: int64 */
            totalClicks: number;
            clicksByCountry: {
                [key: string]: number;
            };
            clicksByDevice: {
                [key: string]: number;
            };
            clicksByBrowser: {
                [key: string]: number;
            };
            clicksOverTime: components["schemas"]["TimeBucket"][];
        };
        TimeBucket: {
            /** Format: date-time */
            timestamp: string;
            /** Format: int64 */
            count: number;
        };
    };
    responses: {
        /** @description Operación exitosa sin payload (data: null) */
        EmptySuccess: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Envelope"] & {
                    /**
                     * @description Sin payload en esta operación (siempre null).
                     * @example null
                     */
                    data?: unknown;
                };
            };
        };
        /** @description Body o parámetros inválidos (`VALIDATION_ERROR`) */
        ValidationError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorEnvelope"];
            };
        };
        /** @description Falta el token o es inválido/expirado (`AUTH_TOKEN_INVALID` / `AUTH_TOKEN_EXPIRED`) */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorEnvelope"];
            };
        };
        /** @description Límite de peticiones excedido (`RATE_LIMIT_EXCEEDED`) */
        RateLimited: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorEnvelope"];
            };
        };
        /** @description Error interno (`INTERNAL_ERROR`) */
        InternalError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorEnvelope"];
            };
        };
    };
    parameters: {
        /** @description Página (default 1) */
        Page: number;
        /** @description Tamaño de página (default 20, máximo 100, se clampea) */
        Limit: number;
        /** @description ID hex de la URL (ObjectID de Mongo) */
        UrlId: string;
        /** @description Código de la URL; si se omite, vista overview de todas las del usuario */
        ShortCodeQuery: string;
        /** @description Rango temporal (default 24h) */
        RangeQuery: "24h" | "7d" | "30d";
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
